<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ocl4acceleo" nsURI="http://www.eclipse.org/ocl/3.1.0/OCL4Acceleo"
    nsPrefix="ocl4acceleo">
  <eClassifiers xsi:type="ecore:EDataType" name="OCLInteger" instanceClassName="java.lang.Integer"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="OCLReal" instanceClassName="java.lang.Double"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="OCLString" instanceClassName="java.lang.String"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="CodeGenHelper" instanceClassName="org.eclipse.ocl.examples.codegen.common.CodeGenHelper"
      abstract="true" interface="true"/>
</ecore:EPackage>
