/**
 *
 * $Id$
 */
package org.eclipse.ocl.examples.xtext.markup.validation;


/**
 * A sample validator interface for {@link org.eclipse.ocl.examples.xtext.markup.FigureElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FigureElementValidator {
	boolean validate();

	boolean validateId(int value);
	boolean validateSrc(String value);
	boolean validateAlt(String value);
	boolean validateDef(String value);
	boolean validateRequiredWidth(String value);
	boolean validateRequiredHeight(String value);
	boolean validateActualWidth(int value);
	boolean validateActualHeight(int value);
}
