/**
 *
 * $Id$
 */
package org.eclipse.ocl.examples.xtext.markup.validation;

import org.eclipse.ocl.examples.xtext.markup.CompoundElement;

/**
 * A sample validator interface for {@link org.eclipse.ocl.examples.xtext.markup.MarkupElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MarkupElementValidator {
	boolean validate();

	boolean validateOwner(CompoundElement value);
	boolean validateUniqueId(int value);
}
