package org.eclipse.ocl.examples.pivot.bodies;

import java.lang.String;
import org.eclipse.jdt.annotation.NonNull;
import org.eclipse.ocl.examples.domain.ids.ClassId;
import org.eclipse.ocl.examples.domain.ids.CollectionTypeId;
import org.eclipse.ocl.examples.domain.ids.EnumerationId;
import org.eclipse.ocl.examples.domain.ids.EnumerationLiteralId;
import org.eclipse.ocl.examples.domain.ids.IdManager;
import org.eclipse.ocl.examples.domain.ids.MetaclassId;
import org.eclipse.ocl.examples.domain.ids.PackageId;
import org.eclipse.ocl.examples.domain.ids.PropertyId;
import org.eclipse.ocl.examples.domain.ids.TypeId;
import org.eclipse.ocl.examples.domain.values.IntegerValue;

public class Constants extends org.eclipse.ocl.examples.domain.values.util.ValuesUtil
{
	public static final @NonNull /*@NonInvalid*/ PackageId PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot = IdManager.INSTANCE.getNsURIPackageId("http://www.eclipse.org/ocl/3.1.0/Pivot", org.eclipse.ocl.examples.pivot.PivotPackage.eINSTANCE);
	public static final @NonNull /*@NonInvalid*/ EnumerationId ENUMid_CollectionKind = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getEnumerationId("CollectionKind");
	public static final @NonNull /*@NonInvalid*/ EnumerationLiteralId ELITid_Bag = ENUMid_CollectionKind.getEnumerationLiteralId("Bag");
	public static final @NonNull /*@NonInvalid*/ EnumerationLiteralId ELITid_Collection = ENUMid_CollectionKind.getEnumerationLiteralId("Collection");
	public static final @NonNull /*@NonInvalid*/ EnumerationLiteralId ELITid_OrderedSet = ENUMid_CollectionKind.getEnumerationLiteralId("OrderedSet");
	public static final @NonNull /*@NonInvalid*/ EnumerationLiteralId ELITid_Sequence = ENUMid_CollectionKind.getEnumerationLiteralId("Sequence");
	public static final @NonNull /*@NonInvalid*/ EnumerationLiteralId ELITid_Set = ENUMid_CollectionKind.getEnumerationLiteralId("Set");
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_BagType = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("BagType");
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_OrderedSetType = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("OrderedSetType");
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_SequenceType = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("SequenceType");
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_SetType = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("SetType");
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_Constraint = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("Constraint");
	public static final @NonNull /*@NonInvalid*/ CollectionTypeId ORD_CLSSid_Constraint = TypeId.ORDERED_SET.getSpecializedId(CLSSid_Constraint);
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_Element = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("Element");
	public static final @NonNull /*@NonInvalid*/ CollectionTypeId SET_CLSSid_Element = TypeId.SET.getSpecializedId(CLSSid_Element);
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_OclElement = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("OclElement");
	public static final @NonNull /*@NonInvalid*/ CollectionTypeId SET_CLSSid_OclElement = TypeId.SET.getSpecializedId(CLSSid_OclElement);
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_OCLExpression = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("OCLExpression");
	public static final @NonNull /*@NonInvalid*/ CollectionTypeId SET_CLSSid_OCLExpression = TypeId.SET.getSpecializedId(CLSSid_OCLExpression);
	public static final @NonNull /*@NonInvalid*/ CollectionTypeId ORD_CLSSid_OCLExpression = TypeId.ORDERED_SET.getSpecializedId(CLSSid_OCLExpression);
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_Variable = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("Variable");
	public static final @NonNull /*@NonInvalid*/ CollectionTypeId ORD_CLSSid_Variable = TypeId.ORDERED_SET.getSpecializedId(CLSSid_Variable);
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_CollectionType = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("CollectionType");
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_CallOperationAction = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("CallOperationAction");
	public static final @NonNull /*@NonInvalid*/ CollectionTypeId SET_CLSSid_CallOperationAction = TypeId.SET.getSpecializedId(CLSSid_CallOperationAction);
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_SendSignalAction = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("SendSignalAction");
	public static final @NonNull /*@NonInvalid*/ CollectionTypeId SET_CLSSid_SendSignalAction = TypeId.SET.getSpecializedId(CLSSid_SendSignalAction);
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_ExpressionInOCL = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("ExpressionInOCL");
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_Parameter = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("Parameter");
	public static final @NonNull /*@NonInvalid*/ CollectionTypeId ORD_CLSSid_Parameter = TypeId.ORDERED_SET.getSpecializedId(CLSSid_Parameter);
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_ParameterableElement = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("ParameterableElement");
	public static final @NonNull /*@NonInvalid*/ MetaclassId METAid_Metaclass = TypeId.METACLASS.getSpecializedId(CLSSid_ParameterableElement);
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_Type = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("Type");
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_Property = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("Property");
	public static final @NonNull /*@NonInvalid*/ CollectionTypeId ORD_CLSSid_Property = TypeId.ORDERED_SET.getSpecializedId(CLSSid_Property);
	public static final @NonNull /*@NonInvalid*/ ClassId CLSSid_NamedElement = PACKid_http_c_s_s_www_eclipse_org_s_ocl_s_3_1_0_s_Pivot.getClassId("NamedElement");
	public static final @NonNull /*@NonInvalid*/ PropertyId PROPid_name = CLSSid_NamedElement.getPropertyId("name");
	public static final @NonNull /*@NonInvalid*/ IntegerValue INT_1 = integerValueOf(1);
	public static final @NonNull /*@NonInvalid*/ String STR_any = "any";
	public static final @NonNull /*@NonInvalid*/ String STR_Boolean = "Boolean";
	public static final @NonNull /*@NonInvalid*/ String STR_closure = "closure";
	public static final @NonNull /*@NonInvalid*/ String STR_collect = "collect";
	public static final @NonNull /*@NonInvalid*/ String STR_collectNested = "collectNested";
	public static final @NonNull /*@NonInvalid*/ String STR_exists = "exists";
	public static final @NonNull /*@NonInvalid*/ String STR_forAll = "forAll";
	public static final @NonNull /*@NonInvalid*/ String STR_isUnique = "isUnique";
	public static final @NonNull /*@NonInvalid*/ String STR_one = "one";
	public static final @NonNull /*@NonInvalid*/ String STR_reject = "reject";
	public static final @NonNull /*@NonInvalid*/ String STR_select = "select";
	public static final @NonNull /*@NonInvalid*/ String STR_sortedBy = "sortedBy";
	public static final @NonNull /*@NonInvalid*/ String STR_body = "body";
	public static final @NonNull /*@NonInvalid*/ String STR_derivation = "derivation";
	public static final @NonNull /*@NonInvalid*/ String STR_initial = "initial";
	public static final @NonNull /*@NonInvalid*/ String STR_name = "name";
}
